In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.0 kB 991.0 kB/s eta 0:00:01
     ---------------------------------------- 61.0/61.0 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.3 MB/s eta 0:00:13
   ---------------------------------------- 0.1/15.8 MB 1.4 MB/s eta 0:00:12
    --------------------------------------- 0.4/15.8 MB 3.0 MB/s eta 0:00:06
   - -------------------------------------- 0.7/15.8 MB 4.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.1/15.8 MB 4.8 MB/s eta 0:00:04
   --- ------------------------------------ 1.4/15.8 MB 5.1 MB/s eta 0:00:03
   ---- ----------------------------------- 1.8/15.8 MB 5.6 MB/s eta 0:00:03
   ----- ---------------------------------- 2.2/15.8 MB 6.1 MB/s eta 0:00:03
   ------ --------------------------------- 2.6/15.8 MB 6.3 MB/s eta 0:00:03
   --

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

1.

In [5]:
array = np.random.randint(1,50,size=(2,2,2))

In [6]:
array

array([[[ 7, 30],
        [34, 16]],

       [[45, 18],
        [31, 23]]])

In [7]:
array.dtype

dtype('int32')

In [8]:
np.ndim(array)

3

In [9]:
array.shape

(2, 2, 2)

In [11]:
array.size

8

-------

1.

In [12]:
a = np.random.randint(1,50,size=(10))

In [13]:
a

array([23, 12, 27, 35, 43, 46, 17, 40,  2,  3])

In [14]:
np.mean(a)

24.8

2.

In [15]:
a = np.array([[1, 2, 3][4,5,6][7,8,9]])
b = np.array([[2, 2, 2][3,3,3][4,4,4]])
ab = np.add(a, b)

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\225710998.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,5,6][7,8,9]])
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\225710998.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,5,6][7,8,9]])
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\225710998.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,5,6]

TypeError: list indices must be integers or slices, not tuple

In [16]:
a = np.array([[1, 2, 3][4,5,6][7,8,9]])


<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\1528246884.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,5,6][7,8,9]])
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\1528246884.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,5,6][7,8,9]])
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\1528246884.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,5,6][7,8,9]])
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\1528246884.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,

TypeError: list indices must be integers or slices, not tuple

In [17]:
a = np.array([[1, 2, 3],[4,5,6],[7,8,9]])


In [18]:
a = np.array([[1, 2, 3][4,5,6][7,8,9]])
b = np.array([[2, 2, 2][3,3,3][4,4,4]])
ab = np.add(a, b)
ab

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\3087161843.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,5,6][7,8,9]])
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\3087161843.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,5,6][7,8,9]])
C:\Users\huser\AppData\Local\Temp\ipykernel_9760\3087161843.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a = np.array([[1, 2, 3][4,5

TypeError: list indices must be integers or slices, not tuple

In [19]:
a = np.array([[1, 2, 3],[4,5,6],[7,8,9]])
b = np.array([[2, 2, 2],[3,3,3],[4,4,4]])
ab = np.add(a, b)
ab

array([[ 3,  4,  5],
       [ 7,  8,  9],
       [11, 12, 13]])

In [20]:
np.mean(ab)

8.0

3.

In [21]:
array = np.random.randint(1,100,size=(20))
big50 = array[array>50]
big50

array([66, 57, 72, 59, 64, 56, 64, 62, 68, 59])

4.

In [22]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.random. shuffle(a)

In [25]:
a

array([ 7,  4,  3,  6,  9, 10,  1,  8,  2,  5])

In [26]:
a[5]

AttributeError: 'numpy.ndarray' object has no attribute 'choice'